name: Build & test

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxcb-cursor-dev libxcb-icccm4 libxcb-xkb1 libxcb-icccm4 libxcb-image0 libxcb-render-util0 libxcb-randr0 libxcb-keysyms1 libxcb-xinerama0 libxcb-xinput-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.*
          modules: 'qt5compat'

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel 4

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        continue-on-error: true
        run: |
          export QT_QPA_PLATFORM=offscreen
          ctest -C ${{ env.BUILD_TYPE }} -E 'Benchmark'

      - name: Debug
        working-directory: ${{ github.workspace }}/build
        run: |
          ldd tests/tests
          cat /home/runner/work/qwtble/qwtble/build/Testing/Temporary/LastTest.log
