name: Build & test

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        qt-version: [6.5.*]
    uses: przemek83/workflows/.github/workflows/build-and-test-qt.yml@main
    with:
      platform: ${{ matrix.platform }}
      use-qt: true
      qt-version: ${{ matrix.qt-version }}